In [5]:
import numpy as np

a = np.array([1,2,4,5])
b=a.tolist()
print(b)


[1, 2, 4, 5]


In [7]:
a=np.eye(10)
print('My array is', a)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


10.0

In [30]:
a = np.array([[1,2],[3,4]])
print(a[a>2])

[3 4]


In [33]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = a+b
print(c)

[[ 6  8]
 [10 12]] 

In [34]:
a = np.array([1,2,3,4])
b = np.mean(a)
print(b)

2.5
